// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Project struct {
	ID          int64  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	CreatedAt   string `db:"created_at" json:"created_at"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
}

type Record struct {
	ID        int64  `db:"id" json:"id"`
	ProjectID int64  `db:"project_id" json:"project_id"`
	Value     int64  `db:"value" json:"value"`
	Timestamp string `db:"timestamp" json:"timestamp"`
}

type Tag struct {
	RecordID   int64  `db:"record_id" json:"record_id"`
	Tag        string `db:"tag" json:"tag"`
	OrderIndex int64  `db:"order_index" json:"order_index"`
}
