// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Record struct {
	ID        string `db:"id" json:"id"`
	Project   string `db:"project" json:"project"`
	Value     int64  `db:"value" json:"value"`
	Timestamp string `db:"timestamp" json:"timestamp"`
}

type Tag struct {
	RecordID string `db:"record_id" json:"record_id"`
	Tag      string `db:"tag" json:"tag"`
}
