// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: records.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const createProject = `-- name: CreateProject :execresult
INSERT INTO projects (name, description, created_at, updated_at)
VALUES (?, ?, ?, ?)
`

type CreateProjectParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	CreatedAt   string `db:"created_at" json:"created_at"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const createRecord = `-- name: CreateRecord :execresult
INSERT INTO records (project_id, value, timestamp)
VALUES (?, ?, ?)
`

type CreateRecordParams struct {
	ProjectID int64  `db:"project_id" json:"project_id"`
	Value     int64  `db:"value" json:"value"`
	Timestamp string `db:"timestamp" json:"timestamp"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRecord, arg.ProjectID, arg.Value, arg.Timestamp)
}

const createRecordTag = `-- name: CreateRecordTag :exec
INSERT INTO tags (record_id, tag, order_index)
VALUES (?, ?, ?)
`

type CreateRecordTagParams struct {
	RecordID   int64  `db:"record_id" json:"record_id"`
	Tag        string `db:"tag" json:"tag"`
	OrderIndex int64  `db:"order_index" json:"order_index"`
}

func (q *Queries) CreateRecordTag(ctx context.Context, arg CreateRecordTagParams) error {
	_, err := q.db.ExecContext(ctx, createRecordTag, arg.RecordID, arg.Tag, arg.OrderIndex)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const deleteRecord = `-- name: DeleteRecord :execresult
DELETE FROM records WHERE id = ?
`

func (q *Queries) DeleteRecord(ctx context.Context, id int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRecord, id)
}

const deleteRecordTags = `-- name: DeleteRecordTags :exec
DELETE FROM tags WHERE record_id = ?
`

func (q *Queries) DeleteRecordTags(ctx context.Context, recordID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecordTags, recordID)
	return err
}

const deleteRecordsUntil = `-- name: DeleteRecordsUntil :execresult
DELETE FROM records WHERE timestamp < ?
`

func (q *Queries) DeleteRecordsUntil(ctx context.Context, timestamp string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRecordsUntil, timestamp)
}

const deleteRecordsUntilByProject = `-- name: DeleteRecordsUntilByProject :execresult
DELETE FROM records WHERE project_id = ? AND timestamp < ?
`

type DeleteRecordsUntilByProjectParams struct {
	ProjectID int64  `db:"project_id" json:"project_id"`
	Timestamp string `db:"timestamp" json:"timestamp"`
}

func (q *Queries) DeleteRecordsUntilByProject(ctx context.Context, arg DeleteRecordsUntilByProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRecordsUntilByProject, arg.ProjectID, arg.Timestamp)
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, created_at, updated_at
FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectTags = `-- name: GetProjectTags :many
SELECT DISTINCT tag
FROM tags t
JOIN records r ON t.record_id = r.id
WHERE r.project_id = ?
ORDER BY tag
`

func (q *Queries) GetProjectTags(ctx context.Context, projectID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getProjectTags, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecord = `-- name: GetRecord :one
SELECT id, project_id, value, timestamp
FROM records
WHERE id = ?
`

func (q *Queries) GetRecord(ctx context.Context, id int64) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Value,
		&i.Timestamp,
	)
	return i, err
}

const getRecordTags = `-- name: GetRecordTags :many
SELECT tag
FROM tags
WHERE record_id = ?
ORDER BY order_index
`

func (q *Queries) GetRecordTags(ctx context.Context, recordID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getRecordTags, recordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, created_at, updated_at
FROM projects
WHERE ? IS NULL OR updated_at < ? OR (updated_at = ? AND name > ?)
ORDER BY updated_at DESC, name
LIMIT ?
`

type ListProjectsParams struct {
	Column1     interface{} `db:"column_1" json:"column_1"`
	UpdatedAt   string      `db:"updated_at" json:"updated_at"`
	UpdatedAt_2 string      `db:"updated_at_2" json:"updated_at_2"`
	Name        string      `db:"name" json:"name"`
	Limit       int64       `db:"limit" json:"limit"`
}

// Cursor-based pagination: uses cursor_updated_at and cursor_name for pagination
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects,
		arg.Column1,
		arg.UpdatedAt,
		arg.UpdatedAt_2,
		arg.Name,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecords = `-- name: ListRecords :many
SELECT
    r.id,
    r.project_id,
    r.value,
    r.timestamp,
    COALESCE((SELECT GROUP_CONCAT(tag, ' ') FROM tags WHERE record_id = r.id ORDER BY order_index), '') as tags
FROM records r
WHERE r.timestamp BETWEEN ? AND ? AND r.project_id = ?
  AND (? IS NULL OR r.timestamp < ? OR (r.timestamp = ? AND r.id > ?))
ORDER BY r.timestamp DESC, r.id
LIMIT ?
`

type ListRecordsParams struct {
	Timestamp   string      `db:"timestamp" json:"timestamp"`
	Timestamp_2 string      `db:"timestamp_2" json:"timestamp_2"`
	ProjectID   int64       `db:"project_id" json:"project_id"`
	Column4     interface{} `db:"column_4" json:"column_4"`
	Timestamp_3 string      `db:"timestamp_3" json:"timestamp_3"`
	Timestamp_4 string      `db:"timestamp_4" json:"timestamp_4"`
	ID          int64       `db:"id" json:"id"`
	Limit       int64       `db:"limit" json:"limit"`
}

type ListRecordsRow struct {
	ID        int64       `db:"id" json:"id"`
	ProjectID int64       `db:"project_id" json:"project_id"`
	Value     int64       `db:"value" json:"value"`
	Timestamp string      `db:"timestamp" json:"timestamp"`
	Tags      interface{} `db:"tags" json:"tags"`
}

// Note: BETWEEN clause must come first due to sqlc bug with SQLite parameter handling
// Optimized query to avoid n+1 problem by using GROUP_CONCAT for tags
// Cursor-based pagination: uses cursor_timestamp and cursor_id for pagination
func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]ListRecordsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecords,
		arg.Timestamp,
		arg.Timestamp_2,
		arg.ProjectID,
		arg.Column4,
		arg.Timestamp_3,
		arg.Timestamp_4,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordsRow{}
	for rows.Next() {
		var i ListRecordsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Value,
			&i.Timestamp,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordsWithTags = `-- name: ListRecordsWithTags :many
SELECT
    r.id,
    r.project_id,
    r.value,
    r.timestamp,
    COALESCE((SELECT GROUP_CONCAT(tag, ' ') FROM tags WHERE record_id = r.id ORDER BY order_index), '') as all_tags
FROM records r
INNER JOIN tags t ON r.id = t.record_id
WHERE r.timestamp BETWEEN ? AND ? AND r.project_id = ?
  AND t.tag IN (/*SLICE:tags*/?)
  AND (? IS NULL OR r.timestamp < ? OR (r.timestamp = ? AND r.id > ?))
GROUP BY r.id, r.project_id, r.value, r.timestamp
HAVING COUNT(DISTINCT t.tag) = CAST(? AS INTEGER)
ORDER BY r.timestamp DESC, r.id
LIMIT ?
`

type ListRecordsWithTagsParams struct {
	Timestamp   string      `db:"timestamp" json:"timestamp"`
	Timestamp_2 string      `db:"timestamp_2" json:"timestamp_2"`
	ProjectID   int64       `db:"project_id" json:"project_id"`
	Tags        []string    `db:"tags" json:"tags"`
	Column5     interface{} `db:"column_5" json:"column_5"`
	Timestamp_3 string      `db:"timestamp_3" json:"timestamp_3"`
	Timestamp_4 string      `db:"timestamp_4" json:"timestamp_4"`
	ID          int64       `db:"id" json:"id"`
	Column9     int64       `db:"column_9" json:"column_9"`
	Limit       int64       `db:"limit" json:"limit"`
}

type ListRecordsWithTagsRow struct {
	ID        int64       `db:"id" json:"id"`
	ProjectID int64       `db:"project_id" json:"project_id"`
	Value     int64       `db:"value" json:"value"`
	Timestamp string      `db:"timestamp" json:"timestamp"`
	AllTags   interface{} `db:"all_tags" json:"all_tags"`
}

// Note: BETWEEN clause must come first due to sqlc bug with SQLite parameter handling
// Returns records that have all of the specified tags
// Optimized query to avoid n+1 problem by using GROUP_CONCAT for all tags
// Cursor-based pagination: uses cursor_timestamp and cursor_id for pagination
func (q *Queries) ListRecordsWithTags(ctx context.Context, arg ListRecordsWithTagsParams) ([]ListRecordsWithTagsRow, error) {
	query := listRecordsWithTags
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Timestamp)
	queryParams = append(queryParams, arg.Timestamp_2)
	queryParams = append(queryParams, arg.ProjectID)
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Column5)
	queryParams = append(queryParams, arg.Timestamp_3)
	queryParams = append(queryParams, arg.Timestamp_4)
	queryParams = append(queryParams, arg.ID)
	queryParams = append(queryParams, arg.Column9)
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecordsWithTagsRow{}
	for rows.Next() {
		var i ListRecordsWithTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Value,
			&i.Timestamp,
			&i.AllTags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :execresult
UPDATE projects SET description = ?, updated_at = ?
WHERE id = ?
`

type UpdateProjectParams struct {
	Description string `db:"description" json:"description"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
	ID          int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProject, arg.Description, arg.UpdatedAt, arg.ID)
}

const updateRecord = `-- name: UpdateRecord :execresult
UPDATE records SET project_id = ?, value = ?, timestamp = ?
WHERE id = ?
`

type UpdateRecordParams struct {
	ProjectID int64  `db:"project_id" json:"project_id"`
	Value     int64  `db:"value" json:"value"`
	Timestamp string `db:"timestamp" json:"timestamp"`
	ID        int64  `db:"id" json:"id"`
}

func (q *Queries) UpdateRecord(ctx context.Context, arg UpdateRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateRecord,
		arg.ProjectID,
		arg.Value,
		arg.Timestamp,
		arg.ID,
	)
}
