// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: records.sql

package db

import (
	"context"
	"database/sql"
)

const createRecord = `-- name: CreateRecord :exec
INSERT INTO records (id, project, value, timestamp)
VALUES (?, ?, ?, ?)
`

type CreateRecordParams struct {
	ID        string `db:"id" json:"id"`
	Project   string `db:"project" json:"project"`
	Value     int64  `db:"value" json:"value"`
	Timestamp string `db:"timestamp" json:"timestamp"`
}

func (q *Queries) CreateRecord(ctx context.Context, arg CreateRecordParams) error {
	_, err := q.db.ExecContext(ctx, createRecord,
		arg.ID,
		arg.Project,
		arg.Value,
		arg.Timestamp,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM records WHERE project = ?
`

func (q *Queries) DeleteProject(ctx context.Context, project string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, project)
	return err
}

const deleteRecord = `-- name: DeleteRecord :execresult
DELETE FROM records WHERE id = ?
`

func (q *Queries) DeleteRecord(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRecord, id)
}

const deleteRecordsUntil = `-- name: DeleteRecordsUntil :execresult
DELETE FROM records WHERE timestamp < ?
`

func (q *Queries) DeleteRecordsUntil(ctx context.Context, timestamp string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRecordsUntil, timestamp)
}

const deleteRecordsUntilByProject = `-- name: DeleteRecordsUntilByProject :execresult
DELETE FROM records WHERE project = ? AND timestamp < ?
`

type DeleteRecordsUntilByProjectParams struct {
	Project   string `db:"project" json:"project"`
	Timestamp string `db:"timestamp" json:"timestamp"`
}

func (q *Queries) DeleteRecordsUntilByProject(ctx context.Context, arg DeleteRecordsUntilByProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteRecordsUntilByProject, arg.Project, arg.Timestamp)
}

const getProjectInfo = `-- name: GetProjectInfo :one
SELECT 
    COUNT(*) as record_count,
    COALESCE(SUM(value), 0) as total_value,
    MIN(timestamp) as first_record_at,
    MAX(timestamp) as last_record_at
FROM records
WHERE project = ?
`

type GetProjectInfoRow struct {
	RecordCount   int64       `db:"record_count" json:"record_count"`
	TotalValue    interface{} `db:"total_value" json:"total_value"`
	FirstRecordAt interface{} `db:"first_record_at" json:"first_record_at"`
	LastRecordAt  interface{} `db:"last_record_at" json:"last_record_at"`
}

func (q *Queries) GetProjectInfo(ctx context.Context, project string) (GetProjectInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectInfo, project)
	var i GetProjectInfoRow
	err := row.Scan(
		&i.RecordCount,
		&i.TotalValue,
		&i.FirstRecordAt,
		&i.LastRecordAt,
	)
	return i, err
}

const getRecord = `-- name: GetRecord :one
SELECT id, project, value, timestamp
FROM records
WHERE id = ?
`

func (q *Queries) GetRecord(ctx context.Context, id string) (Record, error) {
	row := q.db.QueryRowContext(ctx, getRecord, id)
	var i Record
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Value,
		&i.Timestamp,
	)
	return i, err
}

const listRecords = `-- name: ListRecords :many
SELECT id, project, value, timestamp
FROM records
WHERE timestamp BETWEEN ? AND ? AND project = ?
ORDER BY timestamp
`

type ListRecordsParams struct {
	Timestamp   string `db:"timestamp" json:"timestamp"`
	Timestamp_2 string `db:"timestamp_2" json:"timestamp_2"`
	Project     string `db:"project" json:"project"`
}

// Note: BETWEEN clause must come first due to sqlc bug with SQLite parameter handling
func (q *Queries) ListRecords(ctx context.Context, arg ListRecordsParams) ([]Record, error) {
	rows, err := q.db.QueryContext(ctx, listRecords, arg.Timestamp, arg.Timestamp_2, arg.Project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Record{}
	for rows.Next() {
		var i Record
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Value,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
